services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=emanuel
      - POSTGRES_PASSWORD=hejhejhej
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: